### ISSUE TITLE
Get Camera Image / Camera Picture

### ISSUE THREAD

**Issue by mld-ger** [Rajawali/RajawaliVuforia#24]
Is there any way to access the camera image from within the java code?

For my project I have to analyze the image taken by the camera and I only found a workaround to make a preview view with 1x1px in the corner, but this isn't a great solution. And I would like to use the image taken by Rajawali then making another camera instance.

Thank you for your effort and I'm looking forward to your answer.

**Comment by MasDennis** [comment]
Closing this because it was answered by @MrYogi. Please reopen if the problem persists.
