### ISSUE TITLE
Dragging model upon ACTION_MOVE detection.

### ISSUE THREAD

**Issue by sohamdutta13** [Rajawali/RajawaliVuforia#29]
I have been attempting to drag the models. but this only works when the camera is looking down on the target and only in one orientation.
I tried to use the method in https://github.com/MasDennis/Rajawali/issues/753
But it also only works for a certain view.
How do i know what the screen touch coordinates correspond to with respect to rajawali coordinates so i can set the position of my moved model.

**Comment by MasDennis** [comment]
Closing because this because it is old. Please reopen if you still require help with this.
