### ISSUE TITLE
No library found

### ISSUE THREAD

**Issue by NehalkumarMaheshwari** [Rajawali/RajawaliVuforia#32]
05-08 15:50:52.753: I/dalvikvm(1523):   at java.lang.Runtime.nativeLoad(Native Method)
05-08 15:50:52.753: I/dalvikvm(1523):   at java.lang.Runtime.loadLibrary(Runtime.java:368)
05-08 15:50:52.753: I/dalvikvm(1523):   at java.lang.System.loadLibrary(System.java:535)
05-08 15:50:52.753: I/dalvikvm(1523):   at rajawali.vuforia.RajawaliVuforiaActivity.loadLibrary(RajawaliVuforiaActivity.java:441)
05-08 15:50:52.753: I/dalvikvm(1523):   at rajawali.vuforia.RajawaliVuforiaActivity.<clinit>(RajawaliVuforiaActivity.java:60)
05-08 15:50:52.753: I/dalvikvm(1523):   at java.lang.Class.newInstanceImpl(Native Method)
05-08 15:50:52.753: I/dalvikvm(1523):   at java.lang.Class.newInstance(Class.java:1319)
05-08 15:50:52.753: I/dalvikvm(1523):   at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
05-08 15:50:52.753: I/dalvikvm(1523):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2025)
05-08 15:50:52.753: I/dalvikvm(1523):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
05-08 15:50:52.753: I/dalvikvm(1523):   at android.app.ActivityThread.access$700(ActivityThread.java:140)
05-08 15:50:52.753: I/dalvikvm(1523):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
05-08 15:50:52.753: I/dalvikvm(1523):   at android.os.Handler.dispatchMessage(Handler.java:99)
05-08 15:50:52.753: I/dalvikvm(1523):   at android.os.Looper.loop(Looper.java:137)
05-08 15:50:52.753: I/dalvikvm(1523):   at android.app.ActivityThread.main(ActivityThread.java:4935)
05-08 15:50:52.753: I/dalvikvm(1523):   at java.lang.reflect.Method.invokeNative(Native Method)
05-08 15:50:52.753: I/dalvikvm(1523):   at java.lang.reflect.Method.invoke(Method.java:511)
05-08 15:50:52.753: I/dalvikvm(1523):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
05-08 15:50:52.753: I/dalvikvm(1523):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
05-08 15:50:52.753: I/dalvikvm(1523):   at dalvik.system.NativeStart.main(Native Method)

**Comment by MasDennis** [comment]
Closing this as stale. Please reopen if the problem persists.
