### ISSUE TITLE
How to make a object orbit another?

### ISSUE THREAD

**Issue by blodphoenix** [Rajawali/RajawaliVuforia#34]
What I'm trying to do is rotate a md5 model (with a playing animation) around the middle of my scene (really just above the middle of my scene where a have another object). This is my current code and it works just fine as long as you look from above, because as soon as I start to rotate the camera around the object starts rotating sideways (because z axis of the object is changing with the camera).

```Java
Animation3D anim = new RotateAnimation3D(Axis.Z, 360);
anim.setDuration(10000);
anim.setRepeatMode(RepeatMode.INFINITE);
anim.setTransformable3D(mDummy);
registerAnimation(anim);
anim.play();
```

So I guess you can say the code is working as intended but I don't know how to code so that the object rotates around the same point no matter the camera angle.

I know the animation system recently, 8-9april got a bit revamped and I still haven't started using the new codebase but if guys can help me with the old methods displayed here or the new ones I would really appriciate it!

**Comment by MasDennis** [comment]
Closing this as stale. Please reopen if you still need help.
