### ISSUE TITLE
Wrong rotation with negative scale objects

### ISSUE THREAD

**Issue by efrencampillo** [Rajawali/RajawaliVuforia#36]
I detected a new issue, for some 3d models, example md2, that are loaded in Y negative axis,  you need to sale it with Y=-1 to see it right. but when you put the orientation to this kind of objects that are in negative scale, the rotation gets wrong results. I debugged this into the library, and found the wrong result in method Object3d.render()->calculateModelMatrix(parentMatrix);

in this method Object3D i found:
mMMatrix.identity().translate(mPosition).scale(mScale).multiply(mRotationMatrix);
when mScale contains a negative value, gets wrong directions.

i think this can be solved changing the loaded axis, to not modify the operations, because this works fine when are positive scales. i want to avoid the negative scales, but  objects are loaded in y axis inverted.

has anyone an idea how to fix it?

**Comment by MasDennis** [comment]
Closing this issue because it is a v0.9 issue which isn't supported in RajawaliVuforia.
