### ISSUE TITLE
VuforiaRajawali Animations

### ISSUE THREAD

**Issue by jychimaster** [Rajawali/RajawaliVuforia#38]
Hi Dennis
Rajawai and it's integration with Vuforia has been heaven-sent!  Thank you for your contribution.
I have an issue trying to animate models such as rotation, translate, color, etc when a marker or image has been found by the Vuforia AR engine.

I saw this stackoverflow thread:
http://stackoverflow.com/questions/17548861/rajawali-and-vuforia-3d-model-positioning

I tried following your suggestion by creating an empty object3d object. However, it appears that by adding my model as a child to it, it follows the same locking trap that is going on for each frame being rendered.  Specifically it looks like it's trying to do the animation only that it's looping back over and over.

Do you have any simple script for the initScene and foundImageMarker methods so that I can do the simple animation to it's completion without interference?  I hope this makes sense.

Thanks!

**Comment by Francis365** [comment]
Hello,
I tried making SkeletalAnimationObject3D object a child of an empty Object3D, then added the parent to the root of currentScene, now I can't see my animation on the screen. Any idea on what i'm doing wrong
