### ISSUE TITLE
show multiple models with image multiple targets

### ISSUE THREAD

**Issue by jloffredo** [Rajawali/RajawaliVuforia#40]
Hi, I'm having the same issue as issue #9 
( https://github.com/MasDennis/RajawaliVuforia/issues/9 ) 

I have 2 ImageTrackers and I want to see both models when I have both markers. But when one appears the other dissapears.

Perhaps something to do with this? https://developer.vuforia.com/resources/dev-guide/detecting-and-tracking-multiple-targets-simultaneously

Thanks!

**Comment by MasDennis** [comment]
Hi,
This shouldn't be a problem. Please take a look at the example app because it supports multiple targets as well. 
Please reopen if this is still not working for you.

**Comment by jloffredo** [comment]
Multiple targets is no issue. The problem is when you have multiple image targets. You get either one object or the other. Can't see both (or several) when all are image targets.

**Comment by MasDennis** [comment]
Understood. Reopening the issue.

**Comment by MasDennis** [comment]
Hi,
This  change has been implemented. You can use `setMaxSimultaneousImageTargets(int maxSimultaneousImageTargets)` 

https://github.com/Rajawali/RajawaliVuforia/blob/master/RajawaliVuforia/rajawalivuforia/src/main/java/org/rajawali3d/vuforia/RajawaliVuforiaActivity.java#L441
