### ISSUE TITLE
Android Studio compatibility?

### ISSUE THREAD

**Issue by pantaoran** [Rajawali/RajawaliVuforia#41]
I just wanted to try RajawaliVuforia, but I can't get it to work.
Apparently the dependency to Rajawali is based on their master branch rather than the 0.9 release? That's just asking for trouble...

From what I understand, Rajawali was recently switched to Android Studio, but RajawaliVuforia is still an eclipse project. 
How can I use them together now?
Are you planning on porting it to studio soon too?

**Comment by MasDennis** [comment]
The answers to that:
Porting: yes
Soon: yes
I will probably commit it sometime this week.

**Comment by pantaoran** [comment]
Thanks for the quick answer, that's good to know.
Would you happen to know how difficult it is to port the official Vuforia samples to gradle/studio? My current project is closely based on a sample, and I guess I'll have no choice but to switch that project away from Eclipse as well then...

**Comment by MasDennis** [comment]
I've ported the example as well. It was actually quite easy.

**Comment by MasDennis** [comment]
I've just pushed the new files. Please test :goberserk:

**Comment by pantaoran** [comment]
That's awesome, thanks. So sorry, but I won't get to test it anytime soon, I've since started learning OpenGL ES 2.0 and created my own shaders for my Vuforia project.
