### ISSUE TITLE
Upgrade to Vuforia 3.0.9

### ISSUE THREAD

**Issue by MasDennis** [Rajawali/RajawaliVuforia#42]
Upgrade Vuforia from 2.8.8 to 3.0.9. Deliberately not upgrading to 4 because of watermarks and license changes.

**Comment by pantaoran** [comment]
What kind of watermarks and license changes are you talking about?
I only started looking into Vuforia when version 4 was already out, so that's what I'm using now. What was different before?

**Comment by MasDennis** [comment]
> Software made available under certain Service Plans include a watermark Vuforia logo that is required to be displayed in the user interface of the Developer Application pages that interact with or otherwise include the Software even when deployed.  

https://developer.vuforia.com/legal/vuforia-developer-agreement

**Comment by MasDennis** [comment]
Done.
