### ISSUE TITLE
Rajawali imported obj with mtl textures .. fade animation?

### ISSUE THREAD

**Issue by jychimaster** [Rajawali/RajawaliVuforia#44]
I imported an obj model with textures defined in an mtl file in Rajawali.
I would love to be able to do a fade animation much in the same way with ColorAnimation controlling the color and alpha channels.

Is there a way to do this with png texture imported models?
Is there any technique at all to fade a png textured model manipulating the alpha channels the same way with color? I was able to make some head-way manipulating the RGB values with setMaterialColor but it doesn't seem to accomplish anything with alpha.

**Comment by MasDennis** [comment]
You're right, this doesn't seem to exist. It is an essential feature.
Would you mind opening an issue for this in the Rajawali repository? I'll try to get it fixed before the next release. Thanks!
