### ISSUE TITLE
"Cylinder target" and "Multi-targets" implementation

### ISSUE THREAD

**Issue by vortice3D** [Rajawali/RajawaliVuforia#45]
Hi everybody

Although RajawaliVuforia's "readme.md" mentions both "Cylinder target" and "Multi-targets" as supported, the actual code doesn't reflect none of them.

As a first step towards rigid-body recognition (prior to impresive but "watermarked" Vuforia 4.0 solution),  I'm very interested to know if both functionalities are planned to be implemented.

Best regards.

**Comment by MasDennis** [comment]
Hi,
This works the same as image targets. Just check for the marker name in `foundImageMarker()`.

**Comment by vortice3D** [comment]
Hi, first of all, thank you for your time.

Then to have the classic Vuforia soda-can example working, I need to have a cylinder object (NPrism indeed) a little bigger than the real one object, where I'm going to map the soda-can texture.

This way the effect tricks the eye when the orbiting model dissapears behind the 3D model cylinder.
