### ISSUE TITLE
FBX 3d model null pointer

### ISSUE THREAD

**Issue by motionagus** [Rajawali/RajawaliVuforia#67]
i write code in rajawali vuforia like this :
LoaderFBX fbxParser = new LoaderFBX(this,R.raw.millitia_adventure);
			fbxParser.parse();
			testFbxObject = fbxParser.getParsedObject();
			getCurrentScene().addChild(testFbxObject);
			testFbxObject.setVisible(false);

but when the code call renderer it error and say the variable testFbxObject is null pointer

**Comment by ayushvora** [comment]
This is probably because of #1334 and #1335.

**Comment by ayushvora** [comment]
This is probably because of #1334, #1335.

**Comment by motionagus** [comment]
sorry for late reply i, change android studio with unity and its work for fbx
